2024-04-17 16:34:44,863 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:34:54,481 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:38:21,394 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:42:28,001 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:42:38,938 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:42:55,412 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:43:15,837 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:43:32,475 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:45:59,071 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:50:53,820 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:56:58,663 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:56:58,665 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:59:15,675 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 16:59:15,676 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 17:01:01,350 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {'filter_func': <function question_30.<locals>.<lambda> at 0x7efd3074e0d0>} on 6 hosts
2024-04-17 17:01:01,351 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-A': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/devnet-7o8smFAx/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: hello_world() got an unexpected keyword argument 'filter_func'

2024-04-17 17:01:01,351 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-A': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/devnet-7o8smFAx/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: hello_world() got an unexpected keyword argument 'filter_func'

2024-04-17 17:01:01,352 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-A': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/devnet-7o8smFAx/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: hello_world() got an unexpected keyword argument 'filter_func'

2024-04-17 17:01:01,352 - nornir.core.task -    ERROR -      start() - Host 'R1-CPE-BAT-B': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/devnet-7o8smFAx/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: hello_world() got an unexpected keyword argument 'filter_func'

2024-04-17 17:01:01,352 - nornir.core.task -    ERROR -      start() - Host 'R2-CPE-BAT-B': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/devnet-7o8smFAx/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: hello_world() got an unexpected keyword argument 'filter_func'

2024-04-17 17:01:01,353 - nornir.core.task -    ERROR -      start() - Host 'ESW1-CPE-BAT-B': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "/home/cpe/.local/share/virtualenvs/devnet-7o8smFAx/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: hello_world() got an unexpected keyword argument 'filter_func'

2024-04-17 17:04:39,375 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 6 hosts
2024-04-17 17:05:54,369 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 2 hosts
2024-04-17 17:06:15,527 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 2 hosts
